version: '3.4'

services:
  mysql:
    image: 'mysql:5.7.30'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: root
    ports:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  vite:
    build:
      context: ./vite
      dockerfile: Dockerfile
      target: dev
    volumes:
      - /node/app/node_modules
      - ./vite:/node/app
    ports:
      - 3030:3030

  cache:
    image: redis:6

  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./data/uploads:/directus/uploads
      - ./data/snapshots:/directus/snapshots
    depends_on:
      - cache
      - mysql
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mysql'
      DB_HOST: 'mysql'
      DB_PORT: '3306'
      DB_DATABASE: app
      DB_USER: app
      DB_PASSWORD: root

      CACHE_ENABLED: 'true'
      CACHE_AUTO_PURGE: 'true' # set this to true for real time apps
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      CORS_ENABLED: 'true'

      ADMIN_EMAIL: 'app@app.com'
      ADMIN_PASSWORD: 'app'

      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_ABSOLUTE_URI: http://localhost/
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 100M

  web:
    command: /node/node_modules/.bin/nodemon
    environment: 
      NODE_ENV: development
      DIRECTUS_TOKEN: development_token_dont_use_in_production
      CDN_URL: http://static.localhost
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/node/app
      - /node/app/node_modules
    ports:
      - 3000:3000
      - 35729:35729
    depends_on:
      - directus

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: dev
    environment: 
      DOMAIN: localhost
    ports:
      - 80:80
    volumes:
      - ./nginx/dev:/etc/nginx/templates
      - ./vite:/var/www/static:rw,cached
      - ./vite/public:/var/www/public:rw,cached
    depends_on:
      - mysql
      - directus
      - phpmyadmin
      - vite